### ISSUE TITLE
How to access shadow root?

### ISSUE THREAD

**Issue by moebiusmania** [matthewp/haunted#101]
Creating web components with haunted is really cool, but I don't get how to access shadow root for DOM traversal (mainly querySelector). Obviously I'm trying to avoid as much as possible this kind of operations but sometimes you can't run away from them... 

Examples: get the slotted elements or wrapping DOM based libraries.

Any feedback or suggestions are appreciated, thanks.

**Comment by matthewp** [comment]
Hey @moebiusmania, the `this` inside of a Haunted component is the custom element. You can use `this.shadowRoot` to access the shadowRoot. So `querySelector`, etc work there.

```js
function App() {
  useEffect(() => {
    // This is dangerous but go for it!
    this.shadowRoot.querySelector('#special').textContent = 'yolo';
  });
}

customElements.define('my-app', component(App));
```

**Comment by matthewp** [comment]
Also the first argument to the function is the element as well, so if you are using an arrow function and can't use `this`, use the first arg instead. `component((el) => { // use el.shadowRoot })`

**Comment by moebiusmania** [comment]
that's wonderful! thanks a lot!

I'm closing this, but maybe it can be useful to add a couple of lines on the readme 😃
