### ISSUE TITLE
import {...} from 'haunted' does not work anymore as of 4.5.x release

### ISSUE THREAD

**Issue by jdin** [matthewp/haunted#106]
There is a breaking change in the latest release.
While upgrading to haunted **4.5.1** I had to change all my imports to `haunted/lib/haunted` as following:
```javascript
import {html} from "lit-html";
import {component} from "haunted/lib/haunted"; // was: import {component} from "haunted";

const App = () => html`test`;

customElements.define('my-app', component(App));
```

It should be fixed or documentation should be updated. As in a lot of examples you still see `import  from 'haunted'`.

**Comment by matthewp** [comment]
Oh my! Total mistake, of course you shouldn't have to update this. Let me see what is going on.

**Comment by matthewp** [comment]
I don't understand, the package.json main is `lib/haunted.js`: https://github.com/matthewp/haunted/blob/456a079378d852cdbccc198530dfc070cb5af550/package.json#L5-L6

What are you using as your bundler/tool ?

**Comment by jdin** [comment]
I am using parcel. Could be that I did smth. wrong ... I will try to make a project example ...

**Comment by matthewp** [comment]
Ok, I threw together a quick example with rollup and that's working fine: https://gist.github.com/matthewp/d59b2680e840c1bb2944c65ebbeb4a47

Could it be that parcel has cached some things?

**Comment by jdin** [comment]
You can close this ticket. Indeed, it is parcel caching issue.
After cache is deleted it started working.
And what also made me confused - IntelliJ (which I use mostly) somehow does not understand this import and underline it as an error. In Visual Code you do not see it.

**Comment by matthewp** [comment]
Ah, interesting. Cache invalidation is hard!  Wonder if there's anything we can do to tell parcel that the cache should be invalidated ? (I would think the version number change would tell them that).  Anyways, cheers, this one worried me! 🍻
