### ISSUE TITLE
Provide dispatchEvent with `this` context already set

### ISSUE THREAD

**Issue by jdin** [matthewp/haunted#108]
Hi @matthewp,
one more possible enhancement request.

If I want to dispatch a custom event from my web component I have to do smth like this:

```javascript
function myCom({dispatchEvent}) { // <= I cannot use arrow function
 dispatchEvent = dispatchEvent.bind(this); // <= dangerous as I rely on undocumented `this` and ideally can be skipped 
 return html`...`
}
```

Why not dispatchEvent method (and ideally **all the methods from base web component implementation**) has it already **pre-set by haunted**?

**Comment by matthewp** [comment]
Hey @jdin, I don't think I understand, why do you have to bind it? If `this` is not documented that's a mistake, we're not going to break that. The `this` will always be the element instance.

**Comment by jdin** [comment]
Hey @matthewp 
Ideally I think it should work with the following code:
```javascript
const MyComp = ({dispatchEvent}) => { 
 return html`<button @click=${() => dispatchEvent(new CustomEvent('custom-click'))}></button>`
}
```
And it does not work as dispatchEvent does not have `this` context.

I understand that you can do smth like: 
```javascript
function MyComp({}) { 
 return html`<button @click=${() => this.dispatchEvent(new CustomEvent('custom-click'))}></button>`
}
```
But I think it is not so verbose and you should be much more careful with arrow functions.

**Comment by alfredosalzillo** [comment]
You can use `useRef `and the `onLoad `event:
`
function TestComponent() {
   const ref = useRef();
   const dispatchEvent = useCallback((e) => ref.current.dispatchEvent(e));
   return html`<div @load=${(e) => ref.current = e.target )} @click=${() => dispatchEvent(new CustomEvent('custom-click'))}></button>`;
}
`

**Comment by jdin** [comment]
Hi @alfredosalzillo 
Thanks for the example! Indeed it is another way to do it.
But why don't `haunted` would not do it for you as `dispatchEvent` is widely used when you build a web component? Otherwise you need to create unnecessary boilerplate code.

**Comment by alfredosalzillo** [comment]
@jdin I think, passing additional properties to the Component is not a good design solution.
But the this of the current web component could be set in the context, and a hook `useThis` could retrieve it.
For example, we can have:
```javascript
const useDispatchEvent = () => {
  const this = useThis();
  return this.dispatchEvent.bind(this);
}

function TestComponent() {
   const dispatchEvent = useDispatchEvent();
   return html`<button @click=${() => dispatchEvent(new CustomEvent('custom-click'))}>`
}
```

**Comment by jdin** [comment]
Hi, @alfredosalzillo 
Why do you think it is a not a good design? 
[`dispatchEvent`](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/dispatchEvent) is a method in `HtmlElement` class and as any other field it is passed to your component function. 
Try this:
```javascript
 function MyComp({dispatchEvent}) { console.log(dispatchEvent); }
```
and you will see that it is not empty already.
But you cannot call it as you have to bind it first. And I think this `bind` operation should be done in the library.
I think that ideally a component function should not depend on `this` keyword and should be as pure as possible.

**Comment by alfredosalzillo** [comment]
Hi @jdin,
your approach can't be used with a `virtual` component. 
And the fact that that the argument of the `MyComp` is the actual HTML element is undocumented, I think it relies on the `component` function implementation.

An implementation of the `useThis`  (or a better name would be `useHost`) is very simple:

```javascript
const useHost = hook(class HostHook extends Hook {
  constructor(id, el) {
    super(id, el);
    this.el = el;
  }

  update() { return this.el.host; }
});
```

**Comment by jdin** [comment]
hi @alfredosalzillo 

`Virtual` component does not have an element tag so neither implementation will work unless you bind it to some internal tag using `useRef` which is to my mind a bad design as the source in you custom event will be misleading.

If I am not mistaken neither is documented: usage `this` nor what is passed to the component function.

And to be honest I still think that passing all the fields that has your `HtmlElement` implementation  to a component function is the right approach but all the `method` fields should be bound to the right `this` context.  Because any `method` is also a property but just has a `function` type.

@matthewp what is your opinion?

**Comment by matthewp** [comment]
There are several ways you can use dispatchEvent today:

```js
function App() {
  this.dispatchEvent(new Event('click'))
}
```

```js
const App = (el) => {
  el.dispatchEvent(new Event('click'))
}
```

It seems like you're wanting to use destructing (probably for props?). In that case I'd suggest using a normal non-arrow function.  It's just the combination of destructing arguments *and* using an arrow function where you fall into a problem. You can even use destructing + arrow functions this way:

```js
const App = (el) => {
  let { prop1, prop2 } = el;

  el.dispatchEvent(new Event('click'))
}
```

I'd really rather not start special casing certain functions to be bound when there are already normal JavaScript ways to do what you want.

And of course you can always use your own base class if you *really* must have it work this way:

```js
class CustomBase extends HTMLElement {
  constructor() {
    super();
    this.dispatchEvent = this.dispatchEvent.bind(this);
  }
}

const App = component(({dispatchEvent}) => {
  dispatchEvent(new Event('click'));
}, CustomBase);
```

**Comment by jdin** [comment]
@matthewp, thanks for the suggestions!
I understand your point. Actually I am completely fine with the last example. Indeed I can just create my own `component` function where I can override `HTMLElement`.
I will close the this ticket.

**Comment by matthewp** [comment]
@jdin No problem, and thanks for the discussion, keep the ideas coming! 😀 🎃
