### ISSUE TITLE
Starter App Breaking

### ISSUE THREAD

**Issue by azaidi4** [matthewp/haunted#109]
I've been trying to tinker with the demo on codesandbox but all it displays is an empty background. There's no console error. I'm on chrome 75 / Mac.

<img width="1440" alt="Screen Shot 2019-07-19 at 5 57 30 PM" src="https://user-images.githubusercontent.com/26014477/61569788-b6a5c900-aa4e-11e9-851e-cf90c9b7bac1.png">

**Comment by matthewp** [comment]
I updated the starter box. Give it a try and let me know. Thanks for reporting!
