### ISSUE TITLE
A way to declare `observedAttributes` inline

### ISSUE THREAD

**Issue by sgtpep** [matthewp/haunted#110]
How about providing `observedAttributes` like this:

    component(() => html`...`, HTMLElement, { observedAttributes: [...] }));

I'd also either make the second argument optional, or put it into the options object:

    component(() => html`...`, { baseElement: HTMLElement, observedAttributes: [...], ... }));

I could make a PR if this API is fine.

**Comment by matthewp** [comment]
That would be great, thanks!

I think ultimately the options API needs to be revamped. I kind of like putting everything on the function itself, which you currently can only do for observedAttributes. So I think some way to do it either way would be best, perhaps.  

But for now, your suggestion sounds reasonable.
