### ISSUE TITLE
useState update doesn't render after an update has already been queued

### ISSUE THREAD

**Issue by zksward** [matthewp/haunted#114]
I've made a quick demo on codesandbox, linked [here](https://codesandbox.io/embed/relaxed-feistel-4v5wj)

From my understanding and debugging it looks like an update has already been queued before the setTodos call is made (and tries to trigger an update) so the container.update returns. The original update gets rendered, but doesn't have the new state set by setTodos.

I'm new to the use of the library, so I could be doing something wrong or misunderstanding something. Any help/information would be appreciated!

**Comment by matthewp** [comment]
Thanks for reporting!  Does the fact that you are providing a function to setTodos have anything to do with the problem? That is supported, but I'm wondering if the bug is in that code... investigating.

**Comment by matthewp** [comment]
Ah, now I see the issue. You never want to set state within the render function. Instead use `useEffect` to modify the state as a result of the response now being present like so:

```js
    useEffect(() => {
      setTodos(t => {
        let result = [...t, response];
        console.log(result);
        return result;
      });
    }, [ response ]);
```

**Comment by zksward** [comment]
Ah, thanks for the help! That makes sense, I'll go ahead and close then.
