### ISSUE TITLE
Typescript type definitions

### ISSUE THREAD

**Issue by Gladear** [matthewp/haunted#115]
Hi !

I have noted some flaws in the Typescript definitions.
I think types could be more precise, instead of being mostly `any` or `Function`.
I do not have access to my computer at the moment, so I made a list of all the changes that, I think, can improve the type definitions.

Those suggestions are therefore completely untested !

I will test them and make a PR once I have access to my computer.

## Common
- Since the changes in commit 2e46779, the _"typings"_ field in _package.json_ references an unexisting file. It should reference "lib/haunted.d.ts"

## Components
- component: See issue #88
- virtual: I guess it should have the same types as `component`
- withHooks: I didn't find an exported function with this name, maybe it has been deleted ?

## Hooks
- useCallback: `function useCallback(fn: () => void, values?: unknown[]): void`
    - I'm not sure how `useCallback` is supposed to work, as its not documented, so I got inspired by react, but I may have missed some things
    - So, basically, the callback doesn't have any parameter, and doesn't return anything
    - I used the `unknown` type for the second argument as to say "we don't care about the types". `any` could also work, but with `unknown`, we make sure that the function is type safe
- useEffect: `function useEffect(fn: (this: HTMLElement) => (void | () => void), values?: unknown[]): void`
    - In the hook's callback, we can tell that `this` is an HTMLElement. I'm not sure if it is possible to be more precise here, nor if it is necessary, but I'm open to suggestions
    - The function returned shouldn't return a value, which is expressed by `void`
    - Same reasoning about `unknown` as in `useCallback`
- useState: `function useState<S>(initialValue: S | () => S): [S, (newValue: S | (previousValue: S) => S) => void]`
    - Here, we assume that the values of the state will always be of the same types. This should cover all use cases, because the type can be, for example, `string | number` if necessary
    - I chose not to permit the user to pass `undefined` as an initial value without explicitly giving `undefined` as part of the type. This way, the user has full control over the type of the state
- useReducer: `function useReducer<S, A>(this: Hook, reducer: (state: S, action: A) => S, initialState: S): [S, (action: A) => void]`
    - Same assumptions regarding the type of `state` and having the initial state being `undefined` as in `useState`
    - `this` type can be inferred to be a `Hook`, so the user can access `this.id` and `this.el`
- useMemo: `function useMemo<T>(fn: () => T, values?: unknown[]): T`
    - `useMemo` will return the same type as the one returned by the callback
    - Same reasoning about `unknown` as in `useCallback`
- useRef: `function useRef<T>(initialValue: T): { current: T }`
    -  `useRef` will return an object with a property _current_ that type is the same as the initial value

What do you think about those types ?
I'm open to suggestions and enhancements.

**Comment by alfredosalzillo** [comment]
Hi @Gladear,

can you look at the types in the #116?

**Comment by matthewp** [comment]
Closed by #116
