### ISSUE TITLE
can't flip the card view on button click

### ISSUE THREAD

**Issue by bikoocto** [matthewp/haunted#137]
![dndswitch](https://user-images.githubusercontent.com/52039944/64704426-e52ea600-d4cb-11e9-915b-581aa1e2fadc.png)

here is the actual view of the project,
I want to flip the card on clicking the toggle switch .front view is left side first one and the backside second which needs to be shown on the flip the card on button switch clicking.
demo link:  https://codesandbox.io/s/amazing-mcnulty-hj5cc 

using the only CSS not using any npm .
I am just stuck at this, I need help. could somebody answer this?

here is the   Simple design or view pattern of the project.
link:-https://codesandbox.io/s/stupefied-bird-1xnh1
the backside needs to be hidden over the front side.
on button click, it flips the card and shows the backside

**Comment by matthewp** [comment]
Is this related to Haunted? That looks like a React project.

**Comment by bikoocto** [comment]
yes, this one really projects .i am doing for my college semester. can you hel me out?

**Comment by matthewp** [comment]
Are you using Haunted?
