### ISSUE TITLE
Class constructor Hook cannot be invoked without 'new'

### ISSUE THREAD

**Issue by d-Pixie** [matthewp/haunted#138]
Can't get a custom hook to work. I copied the `useState` hook from haunted as a test, to make sure I didn't do anything strange in my code to cause this, and have this code:

```javascript
import { hook, Hook } from 'haunted'

class HookTest extends Hook {
  constructor(id, el, initialValue) {
    super(id, el)
    this.updater = this.updater.bind(this)

    if (typeof initialValue === 'function') {
      initialValue = initialValue()
    }

    this.makeArgs(initialValue)
  }

  update() {
    return this.args
  }

  updater(value) {
    if (typeof value === 'function') {
      const updaterFn = value
      const [previousValue] = this.args
      value = updaterFn(previousValue)
    }

    this.makeArgs(value)
    this.el.update()
  }

  makeArgs(value) {
    this.args = Object.freeze([value, this.updater])
  }
}

const useState = hook(HookTest)

export default useState
```

But when I call it:

```javascript
import useTestHook from 'hooks/theOneIShowedAbove'

const [state, setState] = useTestHook()
```

I get "Class constructor Hook cannot be invoked without 'new'" in the console. All I have managed to read on this seems to indicate that it would be an issue with classes bundled with Babel trying to extend native classes, but I'm not using babel, or any transpilation, on this code and the resulting bundle has the native ES class declaration just as above.

**Comment by matthewp** [comment]
Can you copy/paste what you get when you click on the link to `:3000/commons.js:827`?  Turn off source maps in your devtools so you get the real source. That error sounds a lot like the babel error when extending a real class to me...

**Comment by d-Pixie** [comment]
That leads to the import line from the source above (but now extended to include all imports we use from haunted due to bundling):

```javascript
import { hook, Hook, virtual, useEffect, html, component } from 'haunted';
```

**Comment by d-Pixie** [comment]
That tracks back to the source of haunted:
```javascript
function use(Hook, ...args) {
  let id = notify();
  let hooks = current[hookSymbol];
  
  let hook = hooks.get(id);
  if(!hook) {
    hook = new Hook(id, current, ...args);
    hooks.set(id, hook);
  }

  return hook.update(...args);
}
```
The `hook = new Hook(id, current, ...args);` line.

**Comment by d-Pixie** [comment]
Hmmm ... When looking at this again, without source maps, I see that it leads to a call of `function HookTest(id,el,initialValue){var _this;_this=_Hook.call(this,id,el) ...` and that looks off, it looks transpiled.

So looking further into this I can see that our output, from Rollup, is fine - it is not transpiled. But I'm testing this using Docz and it seems to be including our external script in its bundle and it uses Babel, so it is transpiling our code 😠 

Sorry for the post. I thought I had verified that it wasn't due to Babel transpilation of our code, but apparently our bundling wasn't the only option here ...

**Comment by matthewp** [comment]
No problem, glad you figured it out!
