### ISSUE TITLE
Use preact/react as renderer

### ISSUE THREAD

**Issue by dy** [matthewp/haunted#147]
That's possible to render haunted component's content with react/preact:

```js
<!DOCTYPE html>

<my-counter></my-counter>

<script type="module">
  import { h, Component, render, Fragment } from 'https://unpkg.com/preact?module'
  import htm from 'https://unpkg.com/htm?module'
  import haunted, { useState } from "https://unpkg.com/haunted/haunted.js"

  const html = htm.bind(h);
  const { component } = haunted({ render });

  function Counter() {
    const [count, setCount] = useState(0);

    return html`
      <div id="count">${ count }</div>
      <button type="button" onClick=${() => setCount(count + 1)}>
        Increment
      </button>
    `;
  }

  customElements.define("my-counter", component(Counter));
</script>
```

This example makes haunted fully incorporate react/preact components infrastructure.
Also with preact, virtual components don't make much sense, since regular preact/react components can be used directly.

(not sure what this ticket is about, I guess an integration example, possibly can be a separate doc).

**Comment by matthewp** [comment]
That's interesting that you can do that 😀. But Give that Preact has hooks already why would you add another hooks layer like Haunted?

**Comment by dy** [comment]
I'm curious about 2 potential options:
- (p)react-based web-components (there're libs like [remount](https://github.com/rstacruz/remount), but api is not creation of customElements, like haunted).
- generic hooks with generic renderer - lib, that consumes any renderer (lit, lighter, morphdom etc) and provides react-compatible structure.

**Comment by dy** [comment]
The 1. seems to be trivial, actually:
```js
import { render } from 'preact'

// standard preact component
function Component (props) {
  return <>...</>
}

customElements.define('my-element', class { constructor() { render(<Component/>, this) } })
```
