### ISSUE TITLE
Add example detailing how to fire events

### ISSUE THREAD

**Issue by ChrisBrownie55** [matthewp/haunted#150]
# There should be an example of how to fire events

Currently, there are no examples on how to fire regular or custom events in the README file. I believe it would be beneficial for people new to Haunted (or even web components) to have an example of how to fire events from within their component.

Related to this, on the README there are several examples showing different ways to create a component without speaking to the suttle differences that they create.

For example, there are a few components presented with arrow functions:

```js
const App = ({ name }) => {
 // ...
};

// and

const App = component(() => {
  // ...
});
```

But there's also a regular component function definition:

```js
function Counter() {
  // ...
}

customElements.define('my-counter', component(Counter));
```

**This should be standardized in all examples**. I consider the latter to be the most correct:

## Why does it matter that they're different?

While one might assume showing differently written examples to be harmless or even beneficial, this assumption fails to take into account and explain what either scenarios benefits or losses are.

One significant loss of arrow function components is that **you no longer have access to `this.dispatchEvent`** because of the implicit binding to `this` upon creation.

<br>

### This isn't only important for the component function definition

You might consider documenting that, when trying to do `this.dispatchEvent` or `this.anything` in a callback (that you might attach to a click event or the like), you have to bind the function manually or implicitly via an arrow function as simply creating a `function` definition within your component will bind the function to the element that called it which won't always be your web component.

As you can see in the below example, `fireIncrement` will be calling `dispatchEvent` on the `<button>` that was clicked on, not `Counter`.
```js
function Counter() {
  function fireIncrement() {
    console.log(this);
    // "<button>"
    this.dispatchEvent(/* ... */);
  }
  
  return html`<button @click=${fireIncrement}>Increment</button>`
}
```

However, this could also just be the developer's responsibility to know said information beforehand or it could be placed on a FAQ page of sorts.

**Comment by matthewp** [comment]
I agree, this is a good idea. I prefer to use regular `function` for this reason, it's a little cleaner. Going to mark as a documentation issue.
