### ISSUE TITLE
Standardization of examples in README

### ISSUE THREAD

**Issue by ChrisBrownie55** [matthewp/haunted#151]
# The examples need to be standardized

The examples in the readme are all over the place in terms of being written the same way each time. There are numerous examples most written in a different way than the last. As explained in issue #150 this lack of standardization in examples does bring it's own issues related to firing events.

I propose that all component definitions be re-written to match a style similar to the first example:

```js
function Counter({ myProp }) {
  const [count, setCount] = useState(0);

  return html`
    <div id="count">${count}</div>
    <button type="button" @click=${() => setCount(count + 1)}>Increment</button>
  `;
}

customElements.define('my-counter', component(Counter));
```

### You don't have to get rid of examples of a different style of writing

I'm not saying that it shouldn't be allowed to show different ways to write components in the README but it should be explicitly written as an example of that style. Along with the example should be the style's benefits and drawbacks to help avoid developer confusion.

So you could take something like the following:

> The easiest way to create components is by importing component and creating a custom element like so:
> 
> ```js
> import { component } from 'haunted';
> import { html } from 'lit-html';
> 
> const App = ({ name }) => {
>   return html`Hello ${name}!`;
> };
> 
> customElements.define('my-app', component(App));
> 
> ```

And turn it into a more objective and informative example of how to write the component in a new manner:

> Another way to write your component is with the arrow function syntax (or fat arrow). It offers a more concise and clean way to write your code, however, it does come with a one drawback:
> 
> There's no way to use the `this` keyword to refer to the instance of your web component that is running.
> 
> ```js
> const App = ({ name }) => {
>   console.log(this); // => "undefined"
>   return html`Hello ${name}!`;
> };
> ```

**Comment by matthewp** [comment]
I agree! Using `function` works the best here.
