### ISSUE TITLE
Microsoft Edge compatibility

### ISSUE THREAD

**Issue by justinformentin** [matthewp/haunted#163]
I can't get haunted to work in Edge. I was thinking it was just something I was doing in my project, maybe related to webpack, but I tried loading up a haunted starter app in codesandbox as well and I got the same error. 

`Expected identifier, string or number`

And this error seems to be coming from line 23 in `component.js` 
`else {`
`    this.attachShadow({ mode: 'open', ...shadowRootInit }); <<<<<<THIS LINE  `
`    this._scheduler = new Scheduler(renderer, this.shadowRoot, this);`
`}`
I've tried using every polyfill I can think of as well.

What can I do to get this working in Edge?

**Comment by Gladear** [comment]
Hi,
Edge does not support object spread syntax, that's where the problem comes from.
You should probably use Babel to transpile your code to something Edge can understand, or just don't care and wait for Edge to move to Chromium.

**Comment by justinformentin** [comment]
Hm, I am using babel. I thought preset-env transformed spread, that's weird, I'll look in to that. I tried testing it more and even with the spread, it works in Edge beta on mac and windows, but not the Edge that's shipped with Windows 10.  I'll try forcing spread transformation and see if that helps.
