### ISSUE TITLE
Setting scrollTop on tag using haunted causes an IllegalAccessException

### ISSUE THREAD

**Issue by nlundquist** [matthewp/haunted#166]
When using a haunted component that is a scrollable container, setting the `scrollTop` property on the component instance results in an IllegalAccessException. I believe this is due to `Reflect.set(target, key, value)` here:

https://github.com/matthewp/haunted/blob/142468f93073cb1e99c013a524392eaf90adbefd/src/component.ts#L115

being called with an incorrect `target` argument. While debugging the failing call `target` appeared to be the `HTMLElement` prototype rather than an instance of my component as I'd expect.

I've added a test case for this issue in a branch here: 
https://github.com/nlundquist/haunted/tree/issue-with-scrolltop

**Comment by matthewp** [comment]
Try passing the `receiver` as the 4th argument to Reflect.set

**Comment by mikabytes** [comment]
@matthewp I think this Issue should be fine to close now 👍
