### ISSUE TITLE
Add useContext(Context): ContextValue

### ISSUE THREAD

**Issue by askbeka** [matthewp/haunted#17]
I think this might need context implementation first of all.

I have been thinking about this for quite a while:), but was struggling with design of the API,
I think hooks can simplify the API and finally we can have context in DOM. 

As a solution `CustomEvents` can be used, since the `CustomEvents` are synchronous and you can pass `detail` object to it, parent provider could listen to an event and provide the context value in the same object or consumer can pass subscriber function that provider will call when context value changes.

API can be:

context
```
export const Context = createContext(defaultValue)
```
app
```
import { Context } from 'context';
// ... .provide can be a directive that gets the value and 
// assigns to prop of any DOM element, it can also 
// just wrap whole element, but this way you can easily debug it from elements inspector
html`
   <div .value=${Context.provide(contextValue)}>
       ....someCode
       ....and somewhere in a tree
               <my-element></my-element>
   </div>
`
```
my-element
```
import { Context } from 'context';

function MyElement() {
    const contextValue = useContext(Context);

    return html`
      <div>${contextValue}</div>
    `;
}

customElements.define('my-element', component(MyElement));
```

Relationship can be defined by reference of created context (like shown above) or alternatively by unique string, but then drawback is name collision.

With references drawback is, if` `my-element` is living in different source code, it needs to mock Context and intercept import to inject mocked module, otherwise it is perfect.

Let me know what you think

**Comment by matthewp** [comment]
Not bad! I kind of skipped over context thinking it wasn't really practical in a web component world but you might have convinced me.

One thing though, what listens for the event in order to provide the context? I think instead of putting it on a div or something we might need to create our own element which does the listening.  Maybe like:

```js
import { createContext } from '@matthewp/haunted';

const MyContext = createContext();

function App() {
  const [theme] = useState("dark");

  html`
    <haunted-context .key=${MyContext.key} .value=${theme}>
      <child-element></child-element>
    </haunted-context>
  `;
}
```

I'm not sure what MyContext even would be here.  It might just be a `symbol` and nothing else.

**Comment by askbeka** [comment]
Creating custom element for it crossed my mind too, but unlike React's Provider, custom element provider will be a real DOM node, which does not have visual value, only required because events need to be listened. But in this case thats the only choice we have if we want to use DOM and DOM events to solve context issue, which I think is just perfect and much better that React's solution.

By providing this flexibility, users could reuse existing element or use any other element like div or span
and lossing on any features.

But hey, thats only my opinion and we can provide both options just by abstracting away handling part:)

**Comment by justinfagnani** [comment]
Can't you install the listener directly on the host element itself, without an extra element in the template?

**Comment by matthewp** [comment]
I think you can do that with the way @askbeka implemented it. If you haven't seen the PR: https://github.com/matthewp/haunted/pull/18

@askbeka This should work right?

```j
import { component, createContext, useContext } from '@matthewp/haunted';
import { html } from 'lit-html';

const ThemeContext = createContext();

const MyApp = component(() => {
  return html`<my-child></my-child>`;
}, ThemeContext.Provider);
```

Since `component` takes a base class as the second argument. `component(render, BaseElement)`.

**Comment by askbeka** [comment]
@matthewp Yes, you are right, should work. But I don't see much sense in that, since Provider right now is limited to value property.

PR focuses on max similarity with React's API, which is of course might not be an ideal solution.
Thats why it is in WIP. And there are multiple issues I have found, during implementing it:

- Seems like teardown of effects are not run when element is unmounted.
- Properties are not picked up on components first render, resulting on rerender

**Comment by askbeka** [comment]
@justinfagnani Hi, I got the idea about using customEvents, from one of your talks on Dependency Injection:)

**Comment by matthewp** [comment]
@askbeka Max compatibility with React's API is an idea I support, so we can worry about making it work with the host another time.

As for effects not running on unmount, that's likely a bug and should be done in the disconnectedCallback.  I might look into that myself if you don't get to it first.

**Comment by matthewp** [comment]
I have a PR for that bug: https://github.com/matthewp/haunted/pull/19

**Comment by matthewp** [comment]
@askbeka I merged that fix. Hopefully you see this and don't waste too much time trying to fix it. You can just rebase your branch with master. 😀

**Comment by orlov-vo** [comment]
What if I want build a app only with virtual components - without web components. How to use a context? Maybe need to add directives for `lit-html`?

```js
const ThemeContext = createContext('dark');

const { provide, consume } = ThemeContext;

const App = virtual(() => {
  const [theme, setTheme] = useState('light');

  return html`
      <select value=${theme} @change=${(e) => setTheme(e.target.value)}>
        <option value="dark">Dark</option>
        <option value="light">Light</option>
      </select>
      
      ${provide(theme, html`
        ${provide((value) => value === 'dark' ? 'light' : 'dark', html`
          ${consume((value) => html`<h1>${value}</h1>`)}
        `)}
      `)}
  `;
});

render(App(), document.body);
```

**Comment by matthewp** [comment]
We haven't added context for virtual components yet. Maybe create an issue to discuss?

**Comment by orlov-vo** [comment]
@matthewp I created the issue #40 and updated the example
