### ISSUE TITLE
how to observe attributes which are keywords in js

### ISSUE THREAD

**Issue by fwermus** [matthewp/haunted#175]
I use component iron-page which select the page through html attribute class. I couldn't find a way to observe class attribute in my custom component, because class is a reserved word in JS.

For instance, if I define the following component:

function App({ class }) {
  return `Hello ${class}!`;
}

App.observedAttributes = ['class'];

component(App, { observedAttributes: ['class'] });

It throws "error" in line function App({ class }) , because class couldn't be a variable, but it is a reserved word.

**Comment by jdin** [comment]
I think the following will work:
```javascript
function App({ class:cls }) {
return Hello ${cls}!;
}
```
