### ISSUE TITLE
Why is Component function called when a property value is set to itself?

### ISSUE THREAD

**Issue by micahjon** [matthewp/haunted#192]
Hi,

We're planning on adopting Haunted at [BeFunky](https://www.befunky.com/) and I'm trying to wrap my head around the rendering model. We already use lit-html, but with a setState-like data structure which avoids re-evaluating our Component functions and diffing our templates when the underlying data has not changed. 

This works fine when using the `useState` helper. However, when I set a property on the custom element instance, the Component function is called even if the property value did not change.

Here's a simple Codepen that illustrates the issue:
https://codepen.io/pranksinatra/pen/pogRgKQ?editors=1010

When I set a `color` property on the `<my-app>` component, it re-evaluates the `App()` function, even when the `color` value is already "blue" and is set to "blue" again. 

Maybe this is intentional, but I just want to make sure I understand why things work that way, and if I'm doing something wrong.

Right now I have to do this, from a parent component, which feels kind of gross:
```js
if (referenceToChildComponent.prop !== newValue) {
    referenceToChildComponent.prop = newValue;
}
```
to avoid re-evaluating a child component when nothing has changed.

Thanks! This is a really neat library and our team is excited to start using it.

**Comment by micahjon** [comment]
Did some more digging into this issue. For `useState` and attributes, this is already working perfectly, e.g.


```js
attributeChangedCallback(name: string, oldValue: unknown, newValue: unknown): void {
  if(oldValue === newValue) {
    return;
  }
```
[Link to component.ts:L78](https://github.com/matthewp/haunted/blob/09cef7c19ec3e93fde31538f95eda5ae54940d37/src/component.ts#L78)

But for properties (`reflectiveProp`) we always trigger an update, even if the property value didn't change. This is necessary for the first update, but not for subsequent ones. Here's a simple fix (adding an `isSetup` flag) that passes all tests.

```js
function reflectiveProp<T>(initialValue: T): Readonly<PropertyDescriptor> {
  let value = initialValue;
  let isSetup = false; // NEW
  return Object.freeze({
    enumerable: true,
    configurable: true,
    get(): T {
      return value;
    },
    set(this: Element, newValue: T): void {
      if (isSetup && value === newValue) return; // NEW
      isSetup = true; // NEW
      value = newValue;
      this._scheduler.update();
    }
  })
}
```

@matthewp , does this solution look reasonable?

If so, I'll do some further testing on the components in our webapp that use Haunted and then submit a PR with a test or two so we avoid regression down the road.

**Comment by matthewp** [comment]
I think this sounds fine! Thanks!

**Comment by micahjon** [comment]
Cool, just submitted a PR!

**Comment by micahjon** [comment]
@matthewp , don't mean to bug you, but wondered if you'd had a chance to look at my PR. It passes all existing tests and I added a new test to verify that it behaves as expected. Thanks!

**Comment by matthewp** [comment]
So sorry for missing this, checking it out now.

**Comment by micahjon** [comment]
@matthewp , could we do a new release for this, or are you hoping to include some other bugfixes as well?
