### ISSUE TITLE
Is there any organization for haunted?

### ISSUE THREAD

**Issue by Lodin** [matthewp/haunted#200]
I'm going to port the [react-final-form](https://final-form.org/react) to haunted. Is there any organization I can publish the package under? It would be great to have one to have the nice package name like `@haunted/final-form` instead of old-school variant like `haunted-final-form`.

**Comment by chase-moskal** [comment]
for some reason, aesthetically, i prefer the repos just hanging out on people's personal githubs :)

i guess i just like the anarchy! :laughing:

**Comment by Lodin** [comment]
@chase-moskal, well, I'm actually talking about `npm` organization, not the GitHub one 🙂

**Comment by matthewp** [comment]
There isn't currently but I don't see a problem with creating one.

**Comment by matthewp** [comment]
Going to close
