### ISSUE TITLE
Propblems with creating lit-html, haunted project with typescript

### ISSUE THREAD

**Issue by Eddi-S** [matthewp/haunted#221]
Hi I am probably missing something but cannot figure out what. 
I am trying to create a lit-html, haunted project with typescript.

I have created this simple component which takes one property as input:
```
import {html, component, useState} from 'haunted';

  function MyElement({ test } : { test: boolean })  {
    const [count, setCount] = useState(0);
  
    const name = test ? 'World' : 'Universe';
  
      return html`
        <h1>Hello, ${name}!</h1>
        <button @click=${() => setCount(count + 1)} part="button">
          Click Count: ${count}
        </button>
        <slot></slot>
      `;
  }

  customElements.define("my-element", component(MyElement));
```

But I get this message:

`Argument of type '({ test }: { test: boolean; }) => TemplateResult' is not assignable to parameter of type 'Renderer<HTMLElement>'.
  Types of parameters '__0' and 'host' are incompatible.
    Property 'test' is missing in type 'Component<HTMLElement>' but required in type '{ test: boolean; }'.`

And cannot figure out why - can any of you help?
If I remove the property the code compiles without problems.

**Comment by stevvens** [comment]
You can try this:

```typescript
import {html, component, useState} from 'haunted';

interface Props {
  test: boolean;
}

function MyElement({ test }: Props)  {
  const [count, setCount] = useState(0);

  const name = test ? 'World' : 'Universe';

  return html`
    <h1>Hello, ${name}!</h1>
    <button @click=${() => setCount(count + 1)} part="button">
      Click Count: ${count}
    </button>
    <slot></slot>
  `;
}

customElements.define("my-element", component<HTMLElement & Props>(MyElement));
```

I'm not sure if this is the canonical answer, as it seems like the parameters ought to be inferable as in this helper:

```typescript
function register<Props extends {}>(name: string, comp: (props: Props) => ReturnType<typeof html>) {
  customElements.define(name, component<HTMLElement & Props>(comp));
}

register("my-element", MyElement);
```

**Comment by Eddi-S** [comment]
Thanks @stevvens - that did it! I think it could be helpful with either some examples with haunted in typescript or some documentation for haunted in typescript.
