### ISSUE TITLE
4.8.0 broke builds

### ISSUE THREAD

**Issue by johanventer** [matthewp/haunted#248]
The feature addition in #239 has broken builds for anyone who doesn't have `@lit/reactive-element` installed, as it was only added to `devDependencies`, so it is not installed when you `npm i haunted`.

Looks like it was released in the minor update from 4.7.1 -> 4.8.0. Our packages that rely on haunted and had `^4.7.1` as the dependency version no longer build, as installing dependencies now installs 4.8.0, but we don't use `@lit/reactive-element`, and haunted doesn't install it.

**Comment by bennypowers** [comment]
We could solve this with a `peerDependency` perhaps. can you workaround with `skipLibCheck` for now?

**Comment by matthewp** [comment]
Why a peerDependency and not a normal one? If the code depends on it, we should in the code I think.

**Comment by bennypowers** [comment]
real dep works too. newer yarn and npm will install peerDeps automatically

**Comment by matthewp** [comment]
Should be fixed in 4.8.1
