### ISSUE TITLE
Is Haunted compatible with lit-html v2?

### ISSUE THREAD

**Issue by amant** [matthewp/haunted#257]
Hey,
The code at the bottom with lit-html v2. 
All it renders is `[object Object]` instead of the component.

Compare to lit-html v1, the object return from html`` seems to have changed a bit.
https://github.com/lit/lit/blob/main/packages/lit-html/src/lit-html.ts#L276

Could that be causing the issue with rendering?
Maybe I am doing wrong in the code?

```
<html>
  <my-counter></my-counter>
    import { html } from 'https://unpkg.com/lit@2.0.0-rc.2/index.js?module';
    import { component, useState } from 'https://unpkg.com/haunted/haunted.js';

    function Counter() {
      const [count, setCount] = useState(0);

      return html`
        <div id="count">${count}</div>
        <button type="button" @click=${() => setCount(count + 1)}>
          Increment
        </button>
      `;
    }

    customElements.define('my-counter', component(Counter))
</html>
```

**Comment by bennypowers** [comment]
AFAIK, you can use latest lit-html 1 and 2 together on the same page, *but* you can't compose them together

so it could be that what you're seeing here is haunted internally using lit 1 and you're passing it an incompatible template.

Whereas this might work:

```html
<html>
  <output></output>
  <script type="module">
    import { component, useState, html } from 'https://unpkg.com/haunted/haunted.js';

    function Counter() {
      const [count, setCount] = useState(0);

      return html`
        <div id="count">${count}</div>
        <button type="button" @click=${() => setCount(count + 1)}>
          Increment
        </button>
      `;
    }

    customElements.define('my-counter', component(Counter));
  </script>
  <script type="module">
    import { html, render } from 'https://unpkg.com/lit@2.0.0-rc.2/index.js?module';
    render(html`<my-counter></my-counter>`, document.querySelector("output");
  </script>
</html>
```

**Comment by matthewp** [comment]
Do we know when Lit will be out? I'd like to get Haunted on that soon so there's less confusion around this.

**Comment by matthewp** [comment]
Also it's just Haunted, no .js 😀

**Comment by amant** [comment]
Not sure, when it will be released. Didn't find any roadmap.
Judging from the Lit team's release pattern, I guess it's safe to bet it would be 4th Quarter 2021 :P

**Comment by amant** [comment]
Woohooo this works, need to pass down `render` from lit-html-v2.

```javascript

import { html, render } from 'https://unpkg.com/lit@2.0.0-rc.2/index.js?module'
import haunted, { useState } from 'https://unpkg.com/haunted/core.js'

const { component } = haunted({ render })

function Counter() {
  const [count, setCount] = useState(0)

  return html`
    <div>
    <button type="button" @click=${() => setCount(count + 1)}>
        Increment
    </button>
    </div>
  `
}

customElements.define('my-counter', component(Counter))

 ```

**Comment by bennypowers** [comment]
@amant would you consider a docs pr to the README file?

**Comment by amant** [comment]
@bennypowers Sure thing will do :)

**Comment by matthewp** [comment]
Is this feature not documented already? https://github.com/matthewp/haunted#lighterhtml-etc

Might be worth mentioning there that this can be used for providing your own version of lit-html too.
