### ISSUE TITLE
useHost

### ISSUE THREAD

**Issue by bennypowers** [matthewp/haunted#264]
[atomico](https://atomico.gitbook.io/doc/api/hooks/usehost) offers a `useHost` hook to get a reference to the host element. This could be a solid pick-up for haunted

```js
import { useEffect, useHost } from 'haunted';

const ArrowDispatcher = () => {
  // maybe haunted can skip the `current` b/c of lit?
  // OTOH maybe keep it for the convention,
  // and to support arbitrary vdom renderers?
  const { current } = useHost();
  useEffect(() => {
    current.addEventListener('boop', () => console.log('snoot'));
  }, [current]);
  return html`<button @click=${() => current.dispatchEvent(new Event('boop'))}>Boop</button>`;
}
```

I'm not yet familiar enough with 👻 's guts to say how much faff will be involved in implementing `useHost`

**Comment by matthewp** [comment]
The host (the element) is passed as the first arg, does useHost do anything different?

**Comment by bennypowers** [comment]
Yeah first args is good for my cases.

I wonder if it's good to implement some useHost just for the api saminess? Don't have very strong opinions about this

**Comment by matthewp** [comment]
I sort of think not, it's added code that doesn't really do anything. I'd rather keep it as is.
