### ISSUE TITLE
Make use of directives

### ISSUE THREAD

**Issue by askbeka** [matthewp/haunted#27]
Most of the time application developers do not need shadowDom encapsulation, since they consume ready components and don't need custom elements for each reusable block of code, they can just create functions that return templates, but hooks will be used for sure.

In order to achieve this, lit-html directives could be used, and some internal base Element needs to be created with life cycle hooks, but would this mean creating React over lit-html?

**Comment by matthewp** [comment]
Using the concept outside of custom elements is something @hypercubed brought up as well. All this library really needs is an object to hold hook state and the logic that's in _update which runs the phases. I don't see why we couldn't extract that out and have some alternative starting-point API as a sibling of `component`. I'm sure what that would be called or what it would look like exactly though.

**Comment by matthewp** [comment]
@Hypercubed @askbeka I have a branch that decouples the custom element code from the reactive container part. I created a new api `mount` that can be used to mount a function to an element, without the use of components.

```js
import { mount, useState } from '@matthewp/haunted';

function App() {
  const [state, setState] = useState({ ... });
  return html`...`
}

mount(document.body, App);
```

This isn't *super* useful though since it's just a single component. 

With the reactive container logic decoupled it should now be easy to add some sort of directive support.  Looking at @Hypercubed's code I'm thinking maybe we create a new API, maybe `virtual`, as in virtual components, that uses directives. It might look like:

```js
import { virtual, mount } from '@matthewp/haunted';

const Child = virtual(({ prop }) => {
  return html` ... `
});

const Parent = virtual(() => {
  return html`
    <section>${Child({ prop: 'foo' })}</section>
  `;
});

mount(document.body, Parent);
```

Something like that. What do you think?

**Comment by Hypercubed** [comment]
@matthewp Is `virtual` a lit-html directive somewhat equivalent to my withHooks directive?  If so would the following work:

```js
import { virtual, useState } from '@matthewp/haunted';
import { render, html } from 'lit-html';

const Child = () => {
  return html` ... `
};

const Parent =() => {
  return html`
    <section>${virtual(Child)}</section>
  `;
};

render(virtual(Parent), document.body);
```

BTW... For my `withHooks` implementation I'm tying state to the `NodeParts` object.  By design `lit-html` uses the same `NodeParts` for a given DOM node for every render.

**Comment by askbeka** [comment]
This is also what I had in mind in terms of API.

I foresee people going back and forth converting from component to virtual and vice-versa, especially when there are so many things unclear in the beginning. In my opinion important thing to focus on might be, ease of converting components, which involves consistency in behavior and compatibility with hooks supported by library (ideally and eventually all).

Why it is important is, for example if useContext is supported in a way it is now, which works only with custom elements, someone could just decide to convert it to component, to be able to use it, which is not what we want.

Maybe it is worth to have some HOC that can operate both on virtual and real components. virtual one could be a class that replicates as much as possible of custom-element

**Comment by Hypercubed** [comment]
In that case, I think the `withHooks` would be better naming for that directive... same as Vue.  I've been tempted to publish my `withHooks` directive myself... but I'm not actually using `lit-html` at the moment (but plan to).  If you implement it as part of Haunted I will contribute.  And feel free to take whatever you need from here: https://stackblitz.com/edit/typescript-lit-html-hooks-gyrkjs?file=lit-html-hooks.ts

**Comment by Hypercubed** [comment]
I don't recall if I shared this: https://stackblitz.com/edit/typescript-lit-html-hooks-jm1uhk

Note that when parent template rerenders, the children's state persists.  This is the result of tying state to the `NodePart`.

**Comment by askbeka** [comment]
@matthewp Great, looking forward.
```
render(html`${App()}`, document.body);
```
first argument has to be TemplateResult, so this is possible
