### ISSUE TITLE
Demo in docs broken

### ISSUE THREAD

**Issue by micahjon** [matthewp/haunted#306]
Just a heads up that with lit v2 released, the `html` import in the docs is no longer compatible with Haunted.

The https://unpkg.com/lit-html/lit-html.js import now resolves to https://unpkg.com/lit-html@2.0.0/lit-html.js

Ideally Haunted would play nice w/ lit v2, but in the interim, this is easily fixed by just importing `html` from haunted:

```js
import { component, useState, html } from 'https://unpkg.com/haunted/haunted.js';
```

BTW, the lit v2 build does work. For instance, this will render a button:

```js
import { render, html } from 'https://unpkg.com/lit-html/lit-html.js';

render(html`<button>test</button>`, document.querySelector('my-counter'));
```

I'm guessing the breaking change is `render` appending to a given container instead of replacing the container's contents, as well as accepting some new parameters. More details here: https://lit.dev/docs/releases/upgrade/#lit-html

**Comment by joryphillips** [comment]
Hi, new here, and love this library's API! 

I noticed that following the instructions in PR https://github.com/matthewp/haunted/pull/274/commits/0856b9194637b63ec01e35c677825b25aca88433 also fixes issues with Lit 2 and allows use of the new hotness.

in summary
```
import {html, render} from 'lit';
import haunted, {useEffect} from 'haunted';
```

then
```
const {component} = haunted({render});
```

**Comment by nemethmik** [comment]
It would be great to have a Haunted version that would work with Lit 2.0 out of the box. Currently Haunted cannot be used with component libraries like SAP UI5 Web Components, Shoelace, Vaadin Fusion.

**Comment by bennypowers** [comment]
proximal fix: pin the import urls in the docs
better fix: just cut a haunted release for lit 2

I'm partial to the second, @matthewp

**Comment by matthewp** [comment]
Yep, I'm in favor of getting lit 2 upgrade done as well!

**Comment by matthewp** [comment]
This was done.
