### ISSUE TITLE
Virtual Components can't be conditionally rendered in same part of template

### ISSUE THREAD

**Issue by micahjon** [matthewp/haunted#337]
Today I was building a menu with virtual components and found a bug illustrated in this codepen:
https://codepen.io/pranksinatra/pen/KKXgKPp

It is possible to render multiple virtual components within the same template, but it is not possible to conditionally render them in the same part of the template.

```js
const virtual1 = virtual(() => html`v1`)
const virtual2 = virtual(() => html`v2`)

// This works fine
html`<button>${virtual1()}<button> <button>${virtual2()}<button>`

// This works fine
html`<button>${condition ? virtual1() : 'something else'}<button>`

// But this fails (the first-rendered virtual component is never swapped out with the other one)
html`<button>${condition ? virtual1() : virtual2()}<button>`
```

Thanks again for supporting this library! If it'd be helpful for me to do a deep dive and submit a PR to fix this, let me know.

I suppose there's also a chance it's related to `lit-html v1` and could be resolved once we add support for `lit-html v2`.

**Comment by BeefOnWeck** [comment]
I think this issue can be closed since it was resolved in #369.
