### ISSUE TITLE
Problem with Haunted 4.8.3 and babel loader

### ISSUE THREAD

**Issue by Eddi-S** [matthewp/haunted#367]
Hi I have a NPM package that uses Haunted and LIT-Html 1.4.1, which I then import into a react project.
But after updating haunted to 4.8.3 from 4.8.1 I get this error in the react project:
![image](https://user-images.githubusercontent.com/65396539/156600283-0c0bae6a-8ec0-4374-a5cb-0b6a1bfe98c0.png)
I think it could be solved by configuring babel but I am not sure, does any of you know?

**Comment by bennypowers** [comment]
class fields

**Comment by matthewp** [comment]
I've enabled Discussions. Good place for support sort of questions. https://github.com/matthewp/haunted/discussions
