### ISSUE TITLE
Something like useHost....

### ISSUE THREAD

**Issue by Hypercubed** [matthewp/haunted#37]
Sometimes we may need to access the raw element within the render function.  This is easy enough when using a real component (`this`) but when the render is a arrow function, `this` is undefined.  Do you think it would be useful to add a `useHost` (name TBD) hook?  Something like:

```
  const useHost = hook(class extends Hook {
    constructor(id, el, initialValue) {
      super(id, el);
    }

    update() {
      return this.el.host;
    }
  });
```

**Comment by matthewp** [comment]
The element is also passed as the first argument:

```js
const App = component((el) => {
  return html`${el.className}`
});
```

**Comment by Hypercubed** [comment]
Yep.... looks liek you have this covered.  I missed it in the code.  Thanks!
