### ISSUE TITLE
styling example

### ISSUE THREAD

**Issue by chadams** [matthewp/haunted#379]
an example of styling a component is missing from the docs, How would one go about adding styles to the shadowDom?

**Comment by herrKlein** [comment]
+1
Would love to add tailwind classes. 
Or have an open shadowroot

**Comment by matthewp** [comment]
Thanks, but this is no different from styling in any web component framework. I don't think Haunted's readme is the place to explain how to do everything with web components, just how to use Haunted. Happy to have some links to external docs if anyone has those.
