### ISSUE TITLE
Create component without shadow dom

### ISSUE THREAD

**Issue by nojaf** [matthewp/haunted#434]
Hello, I'd like to create a webcomponent that doesn't have a shadow dom.
In pure Lit I can do something like:
```js
export class GreenCategory extends LitElement {
  
    static properties = {
      tooltip: {type: String},
    };

    createRenderRoot() {
      return this;
    } 
    constructor() {
      super();
      this.tooltip = 'This setting is good to use';
    }
  
    render() {
      return html`<i class="bi bi-check-circle-fill green-recommendation" data-bs-toggle="tooltip" data-bs-custom-class="green-tooltip" data-bs-title="${this.tooltip}"></i>`;
    }
  }
```

The 
```js
    createRenderRoot() {
      return this;
    } 
```
will prevent a shadow dom from being created. (ref: https://lit.dev/docs/components/shadow-dom/#implementing-createrenderroot)

Can I do something similar in haunted?

**Comment by nojaf** [comment]
Ok, silly me, I just found that you can do this:
```js
component(GreenCategory , { useShadowDOM: false})
```

Would you accept a PR to add this somewhere in the documentation?

**Comment by cristinecula** [comment]
@nojaf It's in the docs now: https://hauntedhooks.netlify.app/docs/guides/getting-started/#use

**Comment by nojaf** [comment]
Thanks!
