### ISSUE TITLE
Ensure build before releasing

### ISSUE THREAD

**Issue by rawrmonstar** [matthewp/haunted#46]
I think the last 2 releases weren't built with the merged changes:
  - 3.2.0 doesn't seem to include `useCallback`
  - 3.1.0 doesn't seem to use the `useState` updater function.

I think it might be a good idea to add a `preversion: npm run build` script in the `package.json` that will run a new build whenever `npm version [ major | minor | patch | etc ]` is run to bump the version.

**Comment by matthewp** [comment]
Ah nice, will definitely add this.
