### ISSUE TITLE
Adopting Stylesheets

### ISSUE THREAD

**Issue by bhollis** [matthewp/haunted#473]
Haunted looks really cool! However, one bit that I haven't been able to figure out is how to efficiently adopt stylesheets into the shadow root. For example, here's how Lit's ReactiveElement does it:

https://github.com/lit/lit/blob/main/packages/reactive-element/src/reactive-element.ts#L1016-L1027

They also have a [css tagged template literal](https://github.com/lit/lit/blob/main/packages/reactive-element/src/css-tag.ts) that helps make safe `CSSStyleSheet` objects.

It'd be great if Haunted's `component` had an affordance for adding stylesheets, or perhaps a way to hook into the element's `connectedCallback` to implement such a thing ourselves.

**Comment by bennypowers** [comment]
You could use `useEffect`

```js
import {html, component, useEffect} from 'haunted';

const style = new CSSStyleSheet;
style.replaceSync(/* css */`
                  p { color: blue; }
                  `);


function SimpleGreeting() {
  
  useEffect(() => {
    this.shadowRoot.adoptedStyleSheets = [style]
  });
  
  return html`<p>Hello, ${this.name ?? 'Somebody'}!</p>`;
}

customElements.define('simple-greeting', component(SimpleGreeting, { observedAttributes: ['name'] }));

```

[playground link](https://lit.dev/playground/#gist=89cf26f32f2ce805c2d8cabd5199f144)

**Comment by bhollis** [comment]
That works, thanks!

**Comment by bennypowers** [comment]
see also https://github.com/matthewp/haunted/issues/121
