### ISSUE TITLE
Starter app breaks on Chrome

### ISSUE THREAD

**Issue by luwes** [matthewp/haunted#51]
The starter app is not working on my end on Chrome 71 / Mac.

<img width="1314" alt="screen shot 2019-01-13 at 12 09 58 pm" src="https://user-images.githubusercontent.com/360826/51088328-4c713c00-172c-11e9-8868-09042dac5688.png">

**Comment by matthewp** [comment]
Something changed with Codesandbox and it appears they always transpile to ES5 now :( . I'll look into it.

**Comment by jpray** [comment]
I forked it and got it working with a couple changes.  https://codesandbox.io/s/l4yj5kno5z
The first was to add custom-elements-es5-adapter.  The second was to do 
```
import { component, useState, html } from "haunted";
```
instead of 
```
import { component, useState, html } from "haunted";
import { html } from "lit-html";
```
the need for which appears to be related to https://github.com/matthewp/haunted/issues/49

**Comment by matthewp** [comment]
I updated it on my end, thanks for the pointers @jpray !

The ES5 stuff is a bit annoying, not sure why all of these editors require ES5...
