### ISSUE TITLE
How can custom methods be added to the element?

### ISSUE THREAD

**Issue by luwes** [matthewp/haunted#52]
I was wondering how one would add custom methods / api to the custom element? Thanks

**Comment by matthewp** [comment]
The `component` method returns a class. You can extend this and add your methods/props or whatever else you need. Setting props will cause the functional component to be recalled.

```js
function App({ _name }) {
  return `<span>${_name}</span>`;
}

class AppElement extends component(App) {
  set name(value) {
    this._name = value;
  }
}

customElements.define('my-app', AppElement);
```
