### ISSUE TITLE
example with hyperHTML?

### ISSUE THREAD

**Issue by dakom** [matthewp/haunted#53]
I'm wondering how this fits in with the hyperHTML ecosystem... do I want to basically just use [lighterhtml](https://github.com/WebReflection/lighterhtml) ?

**Comment by matthewp** [comment]
There's an example with hyperHTML here: https://codepen.io/WebReflection/pen/pxXrdy?editors=0010

I'm not familiar with lighterhtml so I'm not sure if it works with that or not.

**Comment by dakom** [comment]
So sticking with that hyperHTML example and making it one level deeper...

This works: https://codepen.io/dakom/pen/robLMg?editors=0011

But this does not: https://codepen.io/dakom/pen/GPLqOM?editors=0011

That second example only wraps the child component in `virtual`... which I believe is necessary according to the docs, and for it to also have hooks?

**Comment by dakom** [comment]
ah okay thanks for the clarification :)

Feel free to close this issue btw

**Comment by matthewp** [comment]
No problem, wish I could be more help but I am not super familiar with hyperHTML.  I know that the author has his own hooks library so maybe that would be more your speed. I'm not positive if it has something equivalent to `virtual` or not, however.  Anyways, cheers 🍻
