### ISSUE TITLE
Attributes

### ISSUE THREAD

**Issue by matthewp** [matthewp/haunted#6]
Haunted doesn't yet support attributes. I feel like this is a missing feature! Ideally you would be able to do:

```js
import { html } from 'lit-html';
import { useMemo } from '@matthewp/haunted';

function FullName({ first, last }) {
  const name = useMemo(() => first + " " + last, [first, last]);

  return html`<span>${name}</span>`
}

function App() {
  return html`<full-name first="Wilbur" last="Phillips"></full-name>`
}

customElements.define('my-app', component(App));
```

Since the functional component receives the element instance as its argument you can destruct to get props. This works for props today but not for attributes.

Options:

# useAttrs

My first thought was to have a `useAttrs(["first", "last"])`. To define attributes. This feels the most "hooks" way of doing it. It would look like:

```js
import { useAttrs } from '@matthewp/haunted';

function FullName() {
  useAttrs(["first", "last"]);
}
```

# Options bag

We could also support passing options into `component()` like so:

```js
import { component } from '@matthewp/haunted';

component(App, { attrs: ["first", "last"] });
```

The downside here is that we would need to run the render() once *before* actually rendering, just to see what attrs are used. We could maybe be sneaky and regex extract these 😲

# Use mutation observers

Lastly we could just not rely on attributeChangedCallback but instead set up a mutation observer for the element and observe attribute changes that way.  In this scenario I think we would automatically set those attributes as property values as well.

The benefit of this method is that you wouldn't need to predefine which attributes your element supports; it would support arbitrary attributes. This method does slightly scare me though.

**Comment by justinfagnani** [comment]
Why not put an `observedAttributes` property on the function?

**Comment by matthewp** [comment]
Oh interesting, I hadn't thought of that, I like it!

**Comment by matthewp** [comment]
I'm going to go with this suggestion for now. I like it because it's the easiest one to deprecate in the future if we find a better way. If we were to go with `useAttrs()` or an options bag that would be more difficult to do away with.  Plus the solution isn't bad at all.
