### ISSUE TITLE
Typescript typings

### ISSUE THREAD

**Issue by Gee5ive** [matthewp/haunted#60]
Are there any plans to add Typescript definition files to the project any time soon?

**Comment by jpray** [comment]
@matthewp, I can take a swing at that if you want.  I'm fairly new to Typescript so I would need a close peer review, but otherwise I'll just follow the style from the lit-html project.

**Comment by Gee5ive** [comment]
@jpray not sure how closely the hooks in haunted are modeled after react in terms of implementation, but they've recently added type definitions for them if that would we of any help. https://github.com/DefinitelyTyped/DefinitelyTyped/blob/834caef36e4fe5c3c4677debe586434000822596/types/react/index.d.ts#L800

**Comment by matthewp** [comment]
Yup, fine with me. The only thing is I don't want the project to be compiled to ES5. So Assuming it can remain at the same ES version as it currently is, no problem.

Can we note a before/after file size? That could be another blocker if it goes up a lot, but hopefully it does not.

**Comment by jpray** [comment]
Without writing the source in Typescript, I think we can just add a haunted.d.ts file that has all the type definitions and a `"typings": "haunted.d.ts",` entry in the package.json.  Will try it out...

**Comment by jpray** [comment]
I'm about 50% done with this, but I do have a couple issues I may need help with.  Here's one:

```
function component(renderer: Function, BaseElement: HTMLElement, options: {
  useShadowDOM: boolean
})

 class MyElement extends HTMLElement {}

component(() => html``, MyElement) // typescript gives error that MyElement is missing properties from HTMLElement and also suggesting that I use "new"
```

Anyone know a fix for this?

**Comment by matthewp** [comment]
I do not know much TypeScript :( Do they have a Slack or something where you can ask questions?

**Comment by jpray** [comment]
Good suggestion.  Found the answer on Gitter:
```
function component(renderer: Function, BaseElement: Function, options: {
  useShadowDOM: boolean
})
```
should have a PR ready soon...
