### ISSUE TITLE
When loading web.js, it should treat lit-html as a sibling

### ISSUE THREAD

**Issue by dustinwtf** [matthewp/haunted#62]
It loads:

```'../node_modules/lit-html/lit-html.js';```

Rather than:

```'../lit-html/lit-html.js';```

Since the two modules are assumed to be in the `node_modules` directory.

**Comment by matthewp** [comment]
Thanks, I think this dates back to when this was a scoped package. I'll fix it.

**Comment by matthewp** [comment]
This was fixed in https://github.com/matthewp/haunted/releases/tag/v4.1.3, thanks for reporting!

**Comment by jpray** [comment]
Sorry to be dense, and to comment on a closed issue, but I am not understanding the use case for web.js.  I read https://github.com/matthewp/haunted/issues/2, but I don't see why 
index.js 
```
import { render, directive } from 'lit-html';
export { html, render } from 'lit-html';
```
and haunted.js 
```
import { render, directive } from 'https://unpkg.com/lit-html@^1.0.0/lit-html.js';
export { html, render } from 'https://unpkg.com/lit-html@^1.0.0/lit-html.js';
```
aren't enough on their own.  @matthewp, can you clarify for me?

**Comment by matthewp** [comment]
Tried to explain in the readme: https://github.com/matthewp/haunted#builds . Perhaps I should expand on that there. web.js is for use in the web browser (where bare specifiers like `lit-html` don't work) in the case where people want to use their own local version of lit-html and not get the latest 1.x like you'll get with unpkg. Or if you just prefer to work offline.

**Comment by jpray** [comment]
Seems a fragile and unoptimized setup, but I understand the use case now. Thanks!

**Comment by matthewp** [comment]
Well, it's optimized for what it's optimized for 😃
