### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by matthewp** [matthewp/haunted#64]
I started working on a website a while back. It's available in the [site branch](https://github.com/matthewp/haunted/tree/site).  it looks like below:

![screen shot 2019-02-18 at 7 36 34 am](https://user-images.githubusercontent.com/361671/52951539-05d8b800-3350-11e9-9944-e6dea54ae2d4.png)

----

I don't think this should be that big of a site. I was thinking of adding a small section below this hero area that shows a code example. Then maybe just link to the repo. 

Oh, and currently it says it's made by me, but really others have been taking on the bulk of the work in the last couple of months so it should say made by collaborators instead. Or maybe we should use ghouls or some other ghostly word...

**Comment by matthewp** [comment]
I own the domain __ahaunted.house__ (tried to get haunted.house but owned by a squattor wanting 10k+ for it) if we ever get around to finishing this.

**Comment by jpray** [comment]
I like it.  I do wonder whether it makes more sense to push all documentation into the readme or have a documentation (examples and API) part of the website.  I'm kinda leaning towards the latter.  A couple other items that maybe could use some thought:
- lit-html and hyperHTML, currently the library definitely is more aligned with lit-html, with secondary support for hyperHTML.  I'd love for it to be agnostic of the rendering library, but not sure yet how much work that would be and how many breaking changes it could introduce.  If someone wants to use hyperHTML with haunted, then they shouldn't also need lit-html.  On the otherhand, hyperHTML/lighterHTML has neverland, so maybe it's not worth tackling...
- There are a number of React hooks that aren't implemented in haunted.  Personally I am ok with this as I think there are substantive differences between web components and react that should influence the hooks patterns in each.  If the goal is to be "React's Hooks API implemented for web components", when we should probably try to implement the full API.  If the goal is changed to something like "Web Component Hooks inspired by React", then not implementing everything React has is okay and we have more freedom to innovate.

**Comment by matthewp** [comment]
@jpray all good points, but I think most of it doesn't pertain to the website. Would you mind filing separate issues to discuss those points?

**Comment by jpray** [comment]
Will do.  Regarding the website,  I do think it needs documentation and examples hosted there.  Otherwise there'd be no point linking to it from the github repo (since it would basically just be itself a link to the github repo).  Especially with the domain name, people searching google will be far more likely to find the github page before they find the website.  I don't think it would take long to take the great info from the readme and turn it into a website.  I'm sold on the idea of web components being good for composing whole web apps, not just leaf nodes as is sometimes expressed.  Hooks really makes this elegant and I think there will be a lot of cool examples that can be shared through the website eventually.

I could help port the readme to the website if the timeframe for doing so is a month or two...  No harm in standing up the simple one in the meantime either.

**Comment by migudev** [comment]
> I own the domain **ahaunted.house** (tried to get haunted.house but owned by a squattor wanting 10k+ for it) if we ever get around to finishing this.

what about using new .dev domains? haunted.dev is available! 🍺

**Comment by gugadev** [comment]
@matthewp how it's going? The last commit was last year. Do you need some help?

**Comment by matthewp** [comment]
@gugadev I haven't worked on it, too many other priorities at the moment. Happy to have some help, what do you have in mind?

**Comment by gugadev** [comment]
@matthewp I have some ideas and for the library itself too, for example, adding a props validator/converter like LitElement. Can you create a open group on [Discord](https://discordapp.com/) to discuss this kind of ideas/proposals/etc.?

Thanks!

**Comment by matthewp** [comment]
Please feel free to post issues here on GitHub to discuss that kind of thing. I think someone else has requested it as well. I sort of want a mixin instead but happy to discuss.

**Comment by gugadev** [comment]
@matthewp Sure. I think the landing is ok and enough. For docs, maybe you can use the repo's Github wiki or go with Docusaurus.

Respect to the mixin, can you explain a bit?

**Comment by matthewp** [comment]
Can we discuss the property stuff here? https://github.com/matthewp/haunted/issues/74. Want to keep this thread about a website.

As for a website, now that I've figured out haunted/core and some other issues, this will probably where I'll spend some more time for a while. Would love to have a website ready for Halloween this year 👻

**Comment by albertosantini** [comment]
Also `haunted.js.org` is nice (and free). 
See https://js.org/.

**Comment by chuanqisun** [comment]
Hey @matthewp, I noticed that this thread has been paused for a while. As a UX developer, I want to contribute to your website as it has helped me build many amazing things. I wonder what you have in mind before you can launch it. Couple of things I can think of:
1. A logo (do you need some graphic designer's help?), or at least a favicon
2. A tag line to summarize why people would want Haunted
3. Link to Github
4. Link to documentation, OR
5. Actual documentation (probably need a static site generator like Gatsby or 11ty to pull off)
5.1 Principle/philosophy
5.2 Guide (quick start, how to do XXX)
5.3 API (various hooks API, custom hook API)
6. Other community things: patreon, discord, etc.

For 5. Actual documentation, are you looking for ways to embed syntax highlighed code in the browser? A couple of things I can think of
1. Just plain code for people to copy
2. Code with live preview (like Code Sandbox embed)
3. Some custom REPL like [Svelte REPL](https://svelte.dev/repl)
4. Search capability (Algolia is free for open source project like this)

For 2. Tag line and 5.1 Principle/philosophy, I wonder what would speak to potential adopters most effectively. It kind of depends on what your project goal is and who you want to appeal to:
1. Should the website focus on convince existing lit-html, web components users to adopt Haunted?
2. Should the web site focus on convince existing React, Preact users to adopt lit-html + Haunted?

One thing to consider is that how likely will the user know about the concept of "Hooks" without already using React. But if users already use React, it's gonna take some effort to convince them that Web component + lit-html is a viable alternative. In that case, is it Haunted's job to make that pitch to users? Or is it lit-html's job? I feel this project is shadowed by the greater React vs. Web component thing. A user has to buy into some many upstream frameworks before understanding the value of Haunted: Web components -> lit-html -> Haunted. I'm curious if there are good strategies to market it from other contributors.

Please let us know what kind of help you need. Thanks!

**Comment by matthewp** [comment]
Hey @chuanqisun! Those are all great ideas. So there's a version of the Haunted website I started a while back in a branch. I need to update that branch to use a SSG, probably Eleventy as that's what I use in most of my projects. I usually do like having the documentation all on the site, so migrating that from the readme to the site I think is a good idea.

How about this, I'll update that branch and get it to the point where anyone can contribute and then let you take over. I won't have a ton of time to contribute large changes myself so I'd like to empower others to do what they think is best. And we can continue discussing it here of course.

**Comment by chuanqisun** [comment]
@shinobi5, I haven't started. Feel free to take a lead on this. I do have some experience in 11ty so I can help too.

**Comment by shinobi5** [comment]
Thanks for the update @chuanqisun. I'm happy to either be a helping hand or take the lead, whatever works. Agree we still need some direction on how to proceed. I'm not familiar with 11ty but making the assumption it's relatively straight forward to pick it up...

**Comment by bennypowers** [comment]
Hey so i put together a site check out #258
