### ISSUE TITLE
initialize the property from attribute value

### ISSUE THREAD

**Issue by aelbore** [matthewp/haunted#73]
```typescript
import { html } from 'lit-html'
import { component, useState } from 'haunted'

function Counter() {
  const [count, setCount] = useState(0);

  return html `
    <div id="count">${count}</div>
    <button type="button" 
      @click=${() => setCount(count + 1)}>
      Increment
    </button> 
  `;
}

customElements.define('my-counter', component(Counter))
```

```html
<my-counter count="10"></my-counter>
```

the count property will have default value of 10

stackblitz
https://stackblitz.com/edit/typescript-p7v7ds

**Comment by aelbore** [comment]
i found out that i can do this (it will initialize the count from attribute), but is there a way to automatically get the value of the attribute?
```typescript
  const [count, setCount] = useState(
    parseInt(this.getAttribute('count'))
  );

```

**Comment by jpray** [comment]
```
function Counter({ count }) {
...
}
Counter.observedAttributes = ["count"];
customElements.define('my-counter', component(Counter))
```

**Comment by aelbore** [comment]
@jpray yes it works but when i click the button it says "setCount" is not a function

**Comment by jpray** [comment]
Assuming you don't want/need the updated value to be reflected in the attribute, then you can do this.

```
import { html } from 'lit-html'
import { component, useState } from 'haunted'

function Counter({ count }) {
  const [_count, setCount] = useState(count);

  return html `
    <div id="count">${_count}</div>
    <button type="button" 
      @click=${() => setCount(_count + 1)}>
      Increment
    </button> 
  `;
}

Counter.observedAttributes = ["count"];

customElements.define('my-counter', component(Counter))
```

**Comment by aelbore** [comment]
@jpray yes i agree about the use of useState, thanks appreciate your help. 
i will try this. i currently working on a testing tool on top of karma, jasmine/mocha without zero configuration. so my plan is to be compatible to all javascript specially with web components.

**Comment by jpray** [comment]
Here is a better example of skipping useState and just using the attribute/property to maintain the value: https://codesandbox.io/s/z275vomrqp . The only smell comes from having to manually convert the string attribute to a number property.  I just submitted #74 to track that.  Can this one be closed?

**Comment by matthewp** [comment]
I think so, thanks for the sandbox 👍

**Comment by aelbore** [comment]
Yes we can close this, thanks for the sample code. Maybe we can hide manually assigning the observedAttibutes, again thanks 👍
