### ISSUE TITLE
Unable to use with Puppeteer

### ISSUE THREAD

**Issue by gugadev** [matthewp/haunted#76]
I have some lit-element components what I'm migrating to haunted and works great, with the exception that cannot be tested using puppeteer.

```javascript
const card = await page.evaluate(_ => document.querySelector('ck-card'))
expect(card).toBeDefined() // test fails due `card` is undefined.
```

Researching  about this, I found the following note in puppeteer docs:

> `evaluate` method returns undefined if the item to return is not a serializable object.

I understand what serialization is, but I don't understand how is related to a DOM element. Can someone explain me a bit please?

PD: LitElement components works good.

**Comment by matthewp** [comment]
Hi, I doubt this is related to Haunted. Happy to help if I can though. I'm not sure why a LitElement would be serializable but a Haunted element to not be.

If you're just attempting to test that the element exists can you return a boolean instead?

```js
page.evaluate(_ => !!document.querySelector('ck-card'))
```

Notice the `!!`.

**Comment by migudev** [comment]
@matthewp Yeah, I'm using that wey. It is a matter of curiosity. Thanks for the support and the lib. 👍

**Comment by matthewp** [comment]
Was this ever figured out? I think I'm going to close as I'm not sure there's anything actionable that we can do. It's also possible that you need to add a wait, as Haunted uses an asynchronous scheduler to render.
