### ISSUE TITLE
Please add the `package.json:module` ESM entry point to support pika

### ISSUE THREAD

**Issue by balupton** [matthewp/haunted#85]
I'm using lit-html and [pika](https://www.pikapkg.com) in an upcoming project, and would like to use Haunted. However, pika only supports ESM packages, which this project is, however there is no `module` field pointing to the ESM entry. Could you please add it. No need to bundle anything with pika.

**Comment by matthewp** [comment]
That was merged. I can't release at the moment, feel free to bug me to release this later if you can remember :)

**Comment by matthewp** [comment]
This was released in 4.3.0: https://github.com/matthewp/haunted/releases/tag/v4.3.0

**Comment by balupton** [comment]
cheers!
