### ISSUE TITLE
Error in readme

### ISSUE THREAD

**Issue by Mateiadrielrafael** [matthewp/haunted#86]
I was looking at the readme, and i saw this:
```ts
import { component } from 'haunted';
import { html } from 'lit-html';

const App = component(({ name }) => {
  return html`Hello ${name}!`;
});

customElements.define('my-app', component(App));
```

Why is it calling component 2 times? I think it should only call it once!

**Comment by matthewp** [comment]
Yup, we can get rid of the second one. Good catch.

**Comment by albertosantini** [comment]
Fixed via https://github.com/matthewp/haunted/commit/0bc689dfd82c7d54c8b0b7abf1b5edcbf17045ec.
You can close it. ;)

**Comment by matthewp** [comment]
Thanks!
