### ISSUE TITLE
Typescript error with context

### ISSUE THREAD

**Issue by idoros** [matthewp/haunted#93]
Exporting context throws a Typescript error when setting the [--declaration
-d flag](https://www.typescriptlang.org/docs/handbook/compiler-options.html). This is needed in order to create typed context that can be imported into dependent projects (generate the `.d.ts` files for the published project).

Example:
```ts
import {createContext } from 'haunted'
export const MyContext = createContext({})
```

Will fail with: `Exported variable 'MyContext' has or is using name 'Context' from external module ".../node_modules/haunted/index" but cannot be named.ts(4023)`

This can be fixed by simply adding `export` for the `Context` interface in [haunted/index.d.ts](https://github.com/matthewp/haunted/blob/a3e19a07af120eb52bcccc40c6092bf4fd233a02/index.d.ts#L25):
```
export interface Context {...}
```

--- Edit:

Actually the other issue with the context types is that it doesn't really support the type that is passed through it. The Context type doesn't offer any generics type for the value. So `useContext`  simply returns `any` instead of the value type of the context.

Would you accept a PR adding this to the Typescript definitions?

**Comment by chase-moskal** [comment]
yes, `Context` should be exported :+1: 

i think it's worth launching a PR for this
